"""Model Scout — Weekly search for best free LLM API models.

Uses BraveAPI to search the web for current free model availability,
compares against the current providers.yml, and generates a report
with recommended updates.

Can be run as a module: python -m llm_router.scout
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests
import yaml

from .config import DEFAULT_PROVIDERS, load_yaml

BRAVE_SEARCH_URL = "https://api.search.brave.com/res/v1/web/search"

# Searches to perform for each free provider
SCOUT_QUERIES = [
    "best free LLM API models {year}",
    "free AI API tier limits {year}",
    "OpenRouter free models list {year}",
    "Google Gemini free API rate limits {year}",
    "Mistral free tier API models {year}",
    "free LLM API no credit card {year}",
    "xAI Grok free API tier {year}",
]


def brave_search(query: str, api_key: str, count: int = 5) -> list[dict]:
    """Perform a Brave web search.

    Returns list of {title, url, description} results.
    """
    headers = {
        "Accept": "application/json",
        "Accept-Encoding": "gzip",
        "X-Subscription-Token": api_key,
    }
    params = {"q": query, "count": count}

    try:
        resp = requests.get(BRAVE_SEARCH_URL, headers=headers, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json()

        results = []
        for item in data.get("web", {}).get("results", []):
            results.append(
                {
                    "title": item.get("title", ""),
                    "url": item.get("url", ""),
                    "description": item.get("description", ""),
                }
            )
        return results
    except Exception as e:
        print(f"[scout] Search failed for '{query}': {e}", file=sys.stderr)
        return []


def gather_search_results(api_key: str) -> dict[str, list[dict]]:
    """Run all scout queries and collect results."""
    year = datetime.now(timezone.utc).year
    all_results = {}

    for query_template in SCOUT_QUERIES:
        query = query_template.format(year=year)
        print(f"[scout] Searching: {query}")
        results = brave_search(query, api_key)
        all_results[query] = results
        print(f"[scout]   Found {len(results)} results")

    return all_results


def generate_report(
    search_results: dict[str, list[dict]],
    current_providers: dict,
) -> str:
    """Generate a markdown report from search results.

    Compares findings against current providers.yml and recommends updates.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    year = datetime.now(timezone.utc).year

    lines = [
        f"# Model Scout Report — {now}",
        "",
        "## Current Free Providers",
        "",
    ]

    # List current free providers
    for pid, config in current_providers.items():
        if config.get("tier") == "free":
            lines.append(
                f"- **{config.get('name', pid)}**: `{config.get('default_model', '?')}`"
            )

    lines.extend(
        [
            "",
            "## Search Results",
            "",
        ]
    )

    for query, results in search_results.items():
        lines.append(f"### {query}")
        lines.append("")
        if not results:
            lines.append("*No results found.*")
        else:
            for r in results[:3]:  # Top 3 per query
                lines.append(f"- [{r['title']}]({r['url']})")
                if r["description"]:
                    lines.append(f"  > {r['description'][:200]}")
        lines.append("")

    lines.extend(
        [
            "## Recommendations",
            "",
            "Review the search results above and consider:",
            "",
            "1. **New free providers** — Are there new free API tiers not in our providers.yml?",
            "2. **Model updates** — Have default free models changed? (e.g., new Gemini version)",
            "3. **Rate limit changes** — Have free tier limits increased or decreased?",
            "4. **Deprecated models** — Are any of our current default models being sunset?",
            "",
            "---",
            "",
            f"*Generated by [llm-router](https://github.com/donjguido/llm-router) model scout on {now}*",
        ]
    )

    return "\n".join(lines)


def run_scout(
    brave_api_key: str | None = None,
    providers_file: str | Path | None = None,
    output_file: str | Path | None = None,
) -> str:
    """Run the full model scout pipeline.

    Args:
        brave_api_key: BraveAPI key. If None, reads from BRAVE_API_KEY env var.
        providers_file: Custom providers.yml to compare against.
        output_file: Where to write the report. If None, prints to stdout.

    Returns:
        The generated report as a string.
    """
    api_key = brave_api_key or os.environ.get("BRAVE_API_KEY")
    if not api_key:
        print("ERROR: No BraveAPI key. Set BRAVE_API_KEY env var.", file=sys.stderr)
        sys.exit(1)

    # Load current providers
    providers_path = Path(providers_file) if providers_file else DEFAULT_PROVIDERS
    providers = load_yaml(providers_path).get("providers", {})

    # Search
    search_results = gather_search_results(api_key)

    # Generate report
    report = generate_report(search_results, providers)

    # Output
    if output_file:
        output_path = Path(output_file)
        output_path.write_text(report, encoding="utf-8")
        print(f"[scout] Report written to {output_path}")
    else:
        print(report)

    # Check if there seem to be notable findings
    total_results = sum(len(r) for r in search_results.values())
    has_updates = total_results > 10  # Rough heuristic

    # Set GitHub Actions output if available
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"updates_needed={'true' if has_updates else 'false'}\n")

    return report


def main():
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="LLM Router Model Scout")
    parser.add_argument(
        "--providers",
        help="Path to providers.yml",
        default=None,
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Output file for report (default: scout-report.md)",
        default="scout-report.md",
    )
    args = parser.parse_args()

    run_scout(providers_file=args.providers, output_file=args.output)


if __name__ == "__main__":
    main()
